# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data

# you can download the dataset from the link: https://drive.google.com/drive/folders/1Z2c3e_rGBGV8wHValqT6Va4uomP246Lv?usp=sharing
# if you download the dataset, you need to store it outside of the project directory and then call it through the method below.
source_data_dirs:
  - ../outside_data/cat
  - ../outside_data/dog

local_data_dirs:
  - data/cat
  - data/dog
